<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#init" data-toc-modified-id="init-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>init</a></span></li><li><span><a href="#read" data-toc-modified-id="read-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>read</a></span></li><li><span><a href="#clns" data-toc-modified-id="clns-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>clns</a></span></li><li><span><a href="#value-counts" data-toc-modified-id="value-counts-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>value counts</a></span><ul class="toc-item"><li><span><a href="#cat" data-toc-modified-id="cat-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>cat</a></span></li></ul></li><li><span><a href="#dist" data-toc-modified-id="dist-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>dist</a></span></li><li><span><a href="#test" data-toc-modified-id="test-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>test</a></span></li></ul></div>

# init

In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
import sys
import os
p = os.path.abspath("../src/")
sys.path.append(p)

In [19]:
from load_data import LoadData

In [20]:
docs = "../docs/"
info = docs + "info/"
finfo = info + "ddl.csv"

data = "../data/"
data_in = data + "in/"
fin = data_in + "train_data.csv"

loader = LoadData(fin, finfo)
loader.load()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,y
id,,,,,,,,,,,,,,,,,,,,,
0,20000.0,2,2,1,24.0,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26.0,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34.0,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,1,2,1,57.0,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
4,50000.0,1,1,2,37.0,0,0,0,0,0,...,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0
5,500000.0,1,1,2,29.0,0,0,0,0,0,...,542653.0,483003.0,473944.0,55000.0,40000.0,38000.0,20239.0,13750.0,13770.0,0
6,100000.0,2,2,2,23.0,0,-1,-1,0,0,...,221.0,-159.0,567.0,380.0,601.0,0.0,581.0,1687.0,1542.0,0
7,140000.0,2,3,1,28.0,0,0,2,0,0,...,12211.0,11793.0,3719.0,3329.0,0.0,432.0,1000.0,1000.0,1000.0,0
8,20000.0,1,3,2,35.0,-2,-2,-2,-2,-1,...,0.0,13007.0,13912.0,0.0,0.0,0.0,13007.0,1122.0,0.0,0
9,200000.0,2,3,2,34.0,0,0,2,0,0,...,2513.0,1828.0,3731.0,2306.0,12.0,50.0,300.0,3738.0,66.0,0
10,260000.0,2,1,2,51.0,-1,-1,-1,-1,-1,...,8517.0,22287.0,13668.0,21818.0,9966.0,8583.0,22301.0,0.0,3640.0,0
11,70000.0,1,2,2,30.0,1,2,2,0,0,...,66782.0,36137.0,36894.0,3200.0,0.0,3000.0,3000.0,1500.0,0.0,1
12,250000.0,1,1,2,29.0,0,0,0,0,0,...,59696.0,56875.0,55512.0,3000.0,3000.0,3000.0,3000.0,3000.0,3000.0,0
13,50000.0,2,3,3,23.0,1,2,0,0,0,...,28771.0,29531.0,30211.0,0.0,1500.0,1100.0,1200.0,1300.0,1100.0,0
14,20000.0,1,1,2,24.0,0,0,2,2,2,...,18338.0,17905.0,19104.0,3200.0,0.0,1500.0,0.0,1650.0,0.0,1
15,360000.0,2,1,1,49.0,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
16,180000.0,2,1,2,29.0,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
17,130000.0,2,3,2,39.0,0,0,0,0,0,...,20616.0,11802.0,930.0,3000.0,1537.0,1000.0,2000.0,930.0,33764.0,0
18,70000.0,2,2,2,26.0,2,0,0,2,2,...,44006.0,46905.0,46012.0,2007.0,3582.0,0.0,3601.0,0.0,1820.0,1
19,450000.0,2,1,1,40.0,-2,-2,-2,-2,-2,...,560.0,0.0,0.0,19428.0,1473.0,560.0,0.0,0.0,1128.0,1
20,90000.0,1,1,2,23.0,0,0,0,-1,0,...,5398.0,6360.0,8292.0,5757.0,0.0,5398.0,1200.0,2045.0,2000.0,0
21,50000.0,1,3,2,23.0,0,0,0,0,0,...,28967.0,29829.0,30046.0,1973.0,1426.0,1001.0,1432.0,1062.0,997.0,0
22,60000.0,1,1,2,27.0,1,-2,-1,-1,-1,...,-57.0,127.0,-189.0,0.0,1000.0,0.0,500.0,0.0,1000.0,1
23,50000.0,2,3,1,47.0,-1,-1,-1,-1,-1,...,2040.0,30430.0,257.0,3415.0,3421.0,2044.0,30430.0,257.0,0.0,0
24,50000.0,1,1,2,26.0,0,0,0,0,0,...,17907.0,18375.0,11400.0,1500.0,1500.0,1000.0,1000.0,1600.0,0.0,0
25,230000.0,2,1,2,27.0,-1,-1,-1,-1,-1,...,15339.0,14307.0,36923.0,17270.0,13281.0,15339.0,14307.0,37292.0,0.0,0
26,50000.0,1,2,2,33.0,2,0,0,0,0,...,22734.0,23217.0,23680.0,1718.0,1500.0,1000.0,1000.0,1000.0,716.0,1
27,100000.0,1,1,2,32.0,0,0,0,0,0,...,80958.0,78703.0,75589.0,3023.0,3511.0,3302.0,3204.0,3200.0,2504.0,0
28,500000.0,2,2,1,54.0,-2,-2,-2,-2,-2,...,7521.0,71439.0,8981.0,4152.0,22827.0,7521.0,71439.0,981.0,51582.0,0
29,160000.0,1,1,2,30.0,-1,-1,-2,-2,-2,...,-923.0,-1488.0,-1884.0,131.0,396.0,396.0,565.0,792.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26970,50000.0,1,2,1,32.0,0,0,0,-1,2,...,50551.0,40590.0,39384.0,2686.0,0.0,50551.0,0.0,1600.0,1500.0,0
26971,20000.0,1,2,2,34.0,0,0,0,0,0,...,13478.0,16978.0,12914.0,2000.0,2000.0,1000.0,5000.0,12914.0,600.0,0
26972,200000.0,1,2,1,33.0,0,0,0,0,0,...,56768.0,58826.0,67577.0,5000.0,2183.0,2059.0,3000.0,9751.0,3000.0,0
26973,360000.0,1,1,1,34.0,-1,-1,-1,0,0,...,49005.0,8676.0,19487.0,52951.0,64535.0,8907.0,53.0,19584.0,16080.0,0
26974,80000.0,1,3,1,36.0,0,0,0,0,0,...,69674.0,71070.0,73612.0,2395.0,2500.0,2530.0,2556.0,3700.0,3000.0,0
26975,190000.0,1,1,1,37.0,0,0,0,0,0,...,29223.0,19616.0,148482.0,2000.0,3869.0,25128.0,10115.0,148482.0,4800.0,0
26976,230000.0,1,2,1,35.0,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
26977,50000.0,1,2,1,37.0,1,2,2,2,0,...,2846.0,1585.0,1324.0,0.0,3000.0,0.0,0.0,1000.0,1000.0,1
26978,220000.0,1,2,1,41.0,0,0,-1,-1,-2,...,5924.0,1759.0,1824.0,8840.0,6643.0,5924.0,1759.0,1824.0,7022.0,0
26979,40000.0,1,2,2,47.0,2,2,3,2,2,...,51259.0,47151.0,46934.0,4000.0,0.0,2000.0,0.0,3520.0,0.0,1
26980,420000.0,1,1,2,34.0,0,0,0,0,0,...,141695.0,144839.0,147954.0,7000.0,7000.0,5500.0,5500.0,5600.0,5000.0,0
26981,310000.0,1,2,1,39.0,0,0,0,0,0,...,219409.0,216540.0,210675.0,10029.0,9218.0,10029.0,8049.0,8040.0,10059.0,0
26982,180000.0,1,1,1,32.0,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
26983,50000.0,1,3,2,42.0,0,0,0,0,0,...,50360.0,19971.0,19694.0,10000.0,4000.0,5000.0,3000.0,4500.0,2000.0,0
26984,50000.0,1,2,1,44.0,1,2,2,2,0,...,28192.0,22676.0,14647.0,2300.0,1700.0,0.0,517.0,503.0,585.0,0
26985,90000.0,1,2,1,36.0,0,0,0,0,0,...,11328.0,12036.0,14329.0,1500.0,1500.0,1500.0,1200.0,2500.0,0.0,1
26986,20000.0,1,2,1,44.0,-2,-2,-2,-2,-2,...,2882.0,9235.0,1719.0,2890.0,2720.0,2890.0,9263.0,1824.0,1701.0,0
26987,30000.0,1,2,2,38.0,-1,-1,-2,-1,-1,...,1993.0,1907.0,3319.0,923.0,2977.0,1999.0,3057.0,3319.0,1000.0,0
26988,240000.0,1,1,2,30.0,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
26989,360000.0,1,1,2,35.0,-1,-1,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
26990,130000.0,1,1,2,34.0,0,0,0,0,0,...,108047.0,93708.0,97353.0,3000.0,2000.0,93000.0,4000.0,5027.0,4005.0,0
26991,150000.0,1,1,2,35.0,-1,-1,-1,-1,-1,...,780.0,0.0,0.0,9054.0,0.0,783.0,0.0,0.0,0.0,0
26992,140000.0,1,2,1,41.0,0,0,0,0,0,...,138262.0,49675.0,46121.0,6000.0,7000.0,4228.0,1505.0,2000.0,2000.0,0
26993,210000.0,1,2,1,34.0,3,2,2,2,2,...,2500.0,2500.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0,1
26994,10000.0,1,3,1,43.0,0,0,0,-2,-2,...,0.0,0.0,0.0,2000.0,0.0,0.0,0.0,0.0,0.0,0
26995,100000.0,1,1,2,38.0,0,-1,-1,0,0,...,70626.0,69473.0,55004.0,2000.0,111784.0,4000.0,3000.0,2000.0,2000.0,0
26996,150000.0,1,3,2,43.0,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
26997,30000.0,1,2,2,37.0,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
26998,80000.0,1,3,1,41.0,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
26999,50000.0,1,2,1,46.0,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [3]:
doc = "../docs/"
info = doc + "info/"

data = "../data/"
data_in = data + "in/"
data_mid = data + "mid/"
data_out = data + "out/"

d_info = info + "ddl.csv"
f_in = data_in + "train_data.csv"

# read

In [10]:
df_info = np.loadtxt(d_info, delimiter=",", encoding="utf-8", dtype=str, skiprows=1)[:23]
df_info.T

array([['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10',
        'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19',
        'X20', 'X21', 'X22', 'X23'],
       ['float', 'str', 'str', 'str', 'float', 'str', 'str', 'str',
        'str', 'str', 'str', 'float', 'float', 'float', 'float', 'float',
        'float', 'float', 'float', 'float', 'float', 'float', 'float']],
      dtype='<U5')

In [26]:
train = pd.read_csv(f_in, index_col="id", dtype=str)

In [27]:
train.T

id,0,1,2,3,4,5,6,7,8,9,...,26990,26991,26992,26993,26994,26995,26996,26997,26998,26999
X1,20000,120000,90000,50000,50000,500000,100000,140000,20000,200000,...,130000,150000,140000,210000,10000,100000,150000,30000,80000,50000
X2,2,2,2,1,1,1,2,2,1,2,...,1,1,1,1,1,1,1,1,1,1
X3,2,2,2,2,1,1,2,3,3,3,...,1,1,2,2,3,1,3,2,3,2
X4,1,2,2,1,2,2,2,1,2,2,...,2,2,1,1,1,2,2,2,1,1
X5,24,26,34,57,37,29,23,28,35,34,...,34,35,41,34,43,38,43,37,41,46
X6,2,-1,0,-1,0,0,0,0,-2,0,...,0,-1,0,3,0,0,-1,4,1,0
X7,2,2,0,0,0,0,-1,0,-2,0,...,0,-1,0,2,0,-1,-1,3,-1,0
X8,-1,0,0,-1,0,0,-1,2,-2,2,...,0,-1,0,2,0,-1,-1,2,0,0
X9,-1,0,0,0,0,0,0,0,-2,0,...,0,-1,0,2,-2,0,-1,-1,0,0
X10,-2,0,0,0,0,0,0,0,-1,0,...,0,-1,0,2,-2,0,0,0,0,0
X11,-2,2,0,0,0,0,-1,0,-1,-1,...,0,-2,0,2,-2,0,0,0,-1,0
X12,3913,2682,29239,8617,64400,367965,11876,11285,0,11073,...,23292,3425,138325,2500,8802,3042,1683,3565,-1645,47929
X13,3102,1725,14027,5670,57069,412023,380,14096,0,9787,...,14077,9009,137142,2500,10400,1427,1828,3356,78379,48905
X14,689,2682,13559,35835,57608,445007,601,12108,0,5535,...,15546,-3,139110,2500,0,102996,3502,2758,76304,49764
X15,0,3272,14331,20940,19394,542653,221,12211,0,2513,...,108047,780,138262,2500,0,70626,8979,20878,52774,36535
X16,0,3455,14948,19146,19619,483003,-159,11793,13007,1828,...,93708,0,49675,2500,0,69473,5190,20582,11855,32428
X17,0,3261,15549,19131,20024,473944,567,3719,13912,3731,...,97353,0,46121,2500,0,55004,0,19357,48944,15313
X18,0,0,1518,2000,2500,55000,380,3329,0,2306,...,3000,9054,6000,0,2000,2000,1837,0,85900,2078
X19,689,1000,1500,36681,1815,40000,601,0,0,12,...,2000,0,7000,0,0,111784,3526,0,3409,1800
X20,0,1000,1000,10000,657,38000,0,432,0,50,...,93000,783,4228,0,0,4000,8998,22000,1178,1430
X21,0,1000,1000,9000,1000,20239,581,1000,13007,300,...,4000,0,1505,0,0,3000,129,4200,1926,1000
X22,0,0,1000,689,1000,13750,1687,1000,1122,3738,...,5027,0,2000,0,0,2000,0,2000,52964,1000
X23,0,2000,5000,679,800,13770,1542,1000,0,66,...,4005,0,2000,0,0,2000,0,3100,1804,1000
y,1,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,1,1

# clns

In [29]:
for col, tp in zip(df_info.T[0], df_info.T[1]):
    train[col] = train[col].astype(tp)

In [30]:
train.dtypes

X1     float64
X2      object
X3      object
X4      object
X5     float64
X6      object
X7      object
X8      object
X9      object
X10     object
X11     object
X12    float64
X13    float64
X14    float64
X15    float64
X16    float64
X17    float64
X18    float64
X19    float64
X20    float64
X21    float64
X22    float64
X23    float64
y       object
dtype: object

# value counts

In [31]:
X = train.drop("y", 1)
y = train.y

In [42]:
cols_obj = []
cols_flt = []

for col in X.columns:
    if X[col].dtype == object:
        cols_obj.append(col)
    elif X[col].dtype == float:
        cols_flt.append(col)
    else:
        raise Exception

## cat

In [44]:
for col in X[cols_obj].columns:
    print(X[col].value_counts())

2    16283
1    10717
Name: X2, dtype: int64
2    12646
1     9505
3     4434
5      244
4      111
6       48
0       12
Name: X3, dtype: int64
2    14358
1    12306
3      290
0       46
Name: X4, dtype: int64
0     13303
-1     5118
1      3310
-2     2439
2      2403
3       296
4        75
5        23
8        17
6         9
7         7
Name: X6, dtype: int64
0     14197
-1     5423
2      3543
-2     3365
3       308
4        87
1        25
5        23
7        18
6        10
8         1
Name: X7, dtype: int64
0     14221
-1     5321
-2     3650
2      3455
3       213
4        71
7        24
6        21
5        18
1         4
8         2
Name: X8, dtype: int64
0     14847
-1     5088
-2     3887
2      2860
3       163
4        62
7        52
5        32
6         5
1         2
8         2
Name: X9, dtype: int64
0     15297
-1     4961
-2     4066
2      2362
3       163
4        78
7        52
5        16
6         4
8         1
Name: X10, dtype: int64
0     14683
-1     5161
-2     4372
2      2498
3       170
4        44
7        42
6        16
5        12
8         2
Name: X11, dtype: int64

In [45]:
X[cols_flt].describe()

,X1,X5,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23
count,27000.000000,27000.000000,27000.000000,27000.000000,2.700000e+04,27000.000000,27000.000000,27000.000000,27000.000000,2.700000e+04,27000.000000,27000.000000,27000.000000,27000.000000
mean,166856.284444,35.502407,51125.750593,49088.579556,4.696029e+04,43247.852074,40345.600926,38894.870926,5644.593222,5.934313e+03,5229.052593,4855.124630,4782.051667,5238.613148
std,129363.239705,9.221539,73398.366141,70906.202371,6.919943e+04,64150.721252,60681.919736,59547.938323,16499.811285,2.360826e+04,17745.539585,15826.973077,15154.386855,17865.467132
min,10000.000000,21.000000,-165580.000000,-69777.000000,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,28.000000,3639.750000,3058.500000,2.743750e+03,2392.750000,1798.500000,1287.000000,1000.000000,8.500000e+02,396.000000,300.000000,272.000000,140.000000
50%,140000.000000,34.000000,22400.000000,21298.000000,2.019050e+04,19114.000000,18219.500000,17179.000000,2100.000000,2.009000e+03,1800.000000,1500.000000,1500.000000,1500.000000
75%,240000.000000,41.000000,66893.250000,63827.250000,5.998400e+04,54537.750000,50211.000000,49243.500000,5007.000000,5.000000e+03,4500.000000,4014.250000,4069.000000,4002.250000
max,1000000.000000,79.000000,964511.000000,983931.000000,1.664089e+06,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.000000,621000.000000,426529.000000,528666.000000

In [48]:
X.isna().sum()

X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
dtype: int64

# dist

# test